name: deply and test


permissions:
  contents: write


on:
  push:
    branches: 
      - "master"
jobs:
    build_and_test: 
        runs-on: ubuntu-latest


        strategy:
          matrix:
            node-version: [ 18.x]


        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup node 
              uses: actions/setup-node@v4
              with: 
                node-version: ${{ matrix.node-version}}
            - name: Install 
              run: npm  ci --legacy-peer-deps # use ci for clean install 

            - name: Build
              run: npm run build
            - name: deploy 
              run: 
                 npm run ng -- deploy --base-href=/p5-sketch/ --name="Asumie-code" --email=darkeangel.1998.ia@gmail.com
                 --repo=Asumie-code/p5-sketches